version: '3'
networks:
  ged_network:
    name: laminas_network

services:
  ged_exp_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laminas_php
    volumes:
      - .:/var/www
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - ged_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:5.7
    container_name: laminas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laminas
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - laminas_network
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
